---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    # dumper.rb
    - dec843d4724d26c64427d1037a2ea4f1
    # aes_crypt.rb
    - 33893778c027f4ce2aaef293c8eb00e0
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/
