AllCops:
  Exclude:
    - spec/**/*

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Max: 160

Metrics/ClassLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  EnforcedStyle: comparison
