language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - jruby-9.2.5.0
env:
  global:
    - JRUBY_OPTS="--debug"
after_success:
  - bundle exec codeclimate-test-reporter
